tasks:
  - init: |
      npm install
      cd /workspace
      wget https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_extended_0.85.0_Linux-64bit.tar.gz
      mkdir hugo
      tar -zxvf hugo_extended_0.85.0_Linux-64bit.tar.gz -C hugo
      export PATH=$PATH:/workspace/hugo
    command: npm run dev

ports:
  - port: 1313
    onOpen: open-browser
