tasks:
  - init: |
      git checkout dev
      npm install
      echo "" >> .env
      mkdir ./.hugo/ && cd ./.hugo/
      wget https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_extended_0.85.0_Linux-64bit.tar.gz
      tar -zxvf hugo_extended_0.85.0_Linux-64bit.tar.gz
      export PATH=$PATH:`pwd`
      cd ../
    command: npm run dev

ports:
  - port: 1313
    onOpen: open-browser
